name: popme
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  provider: ^6.0.3
  animate_do: ^2.1.0
  carousel_slider: ^4.1.1
  video_player: ^2.4.7
  flutter_svg: ^1.1.5
  circle_progress_bar: ^0.1.2
  salomon_bottom_bar: ^3.3.1
  blurrycontainer: ^1.0.2
  bubble: ^1.2.1
  badges: ^2.0.3
  # flutter_dash: ^1.0.0
  # camera: ^0.10.0+1
  # pdf: ^3.8.3
  # path_provider: ^2.0.11
  # image_picker: ^0.8.5+3
  intl: ^0.17.0
  flutter_lorem: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/




  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

